### ISSUE TITLE
NO_OCI_CONNECTION and other intermittent issues

### ISSUE THREAD

**Issue by ghost** [cwmiller/broadworks-connector-net#2]
Hi Chase,

First off I want to say thanks for this great piece of software. It has saved me countless hours in interfacing with the Broadsoft API.
I have just noticed a couple issues that I was hoping you'd be able to shed some light on.

I am running into an issue where after a few minutes of running requests successfully I start to get exceptions thrown from various requests. There is no request in particular that causes the issue. It just seems to happen randomly if you are making many calls in a short period of time.

I am seeing the following intermittent errors:

1. NO_OCS_CONNECTION
    - The remediation I have attempted here is that when I get this error I reauthenticate with broadsoft doing an 
     AuthenticationRequest and then a LoginRequest. The problem here is that the LoginRequest itself is sometimes throwing this 
     same error. There is no further information to this error and I have not found anything useful online. I have also tested this on multiple machines including a rather beefy EC2 instance sitting in AWS that should not be experiencing connection issues.

2. INVALID_REQUEST
    - This one also doesnt provide any further clarity on what may be causing the issue. It happens randomly and the requests that it is failing on are valid. If you try it again manually for just the one individual call then it succeeds as expected.

3. Password is invalid
   - This one is very strange. It happens randomly and when viewing the request at the time the password that was sent to the LoginRequest was the correct password. This is very intermittent and is causing our account to be disabled on broadsoft.

I have searched tirelessly online for something to help me with the above but I have come very short. I am hoping you have encountered some of these issues while developing this library and could shed some light on it for me.

Anything you can add would be greatly appreciated.

Thanks,
Aaron

**Comment by cwmiller** [comment]
I'm glad the library has been of use to you!

In my experience, I've seen the first two errors before. 

I've seen NO_OCS_CONNECTION before when I was communicating to OCI over the SOAP interface. I'm not an expert on this (I don't know much about managing a BroadWorks infrastructure, just utilizing the API), but at the time I believed it was an issue on the server-side between the HTTP server and OCS. After it started happening more and more, I switched over to accessing the API using the TCP method instead of SOAP and stopped having issues. Maybe there is something more to it though.. but it is hard to debug because like you I would only run into it randomly.

For INVALID_REQUEST, this gets thrown by the server if you're trying to make an OCI call before the login process has finished. This can happen if you don't ``await`` each method on ``OcipClient``, or possibly when sharing a single instance of ``OcipClient`` to multiple consumers using it in parallel.

I don't believe I've ran into the password issue you're experiencing. My only recommendations for this are what I said for INVALID_REQUEST (ensure you ``await`` all methods, don't use a single instance in parallel). You may try manually triggering the login by calling ``await ocipClient.LoginAsync()`` before any other method calls to ensure the login process is completed.

I hope these thoughts are useful to you.

**Comment by ghost** [comment]
Hi Chase,

Thanks for the excellent reply. It has certainly give me some stuff to think about. I will definitely take a look at the TCP method of accessing the API as you mentioned you had more luck with that one.

I have managed to resolve all the issues I was seeing by no longer using a single instance of the `OcipClient ` across the various threads but now instead I am creating a new instance per thread which seems to be working far more reliably.

Thanks again for your response.

Much Appreciated,
Aaron
